### ISSUE TITLE
Xna 1.0 conversion failed

### ISSUE THREAD

**Issue by Beyley** [Athari/XnaConvert#12]
Attempting to convert the files from the 2007 version of the rhythm game osu! causes an error to happen (it uses Xna 1.0 according to the version in the Xna binary ![dnSpy-x86_X21KIEc0kI](https://user-images.githubusercontent.com/34501060/101989988-d0a20600-3c58-11eb-898f-a26ad938c6a2.png) ), and when attempting to convert an xnb file from it, it spits out an error

```
C:\Users\Ep1c_M1n10n\Downloads\Alba.XnaConvert.0.1.2>Alba.XnaConvert.exe convert -v 1.0 -i star.xnb -o star.png
Loading content loader for 'XNA' with version '1.0'...
Unexpected error!
The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.  1) The method call is invalid.  Resulting in: An exception occurred while trying to create an instance of type 'Alba.XnaConvert.Loader.Xna10.ContentService'.  Resulting in: Cannot activate part 'Alba.XnaConvert.Loader.Xna10.ContentService'. Element: Alba.XnaConvert.Loader.Xna10.ContentService -->  Alba.XnaConvert.Loader.Xna10.ContentService -->  DirectoryCatalog (Path=".")  Resulting in: Cannot get export 'Alba.XnaConvert.Loader.Xna10.ContentService (ContractName="Alba.XnaConvert.Common.IContentService")' from part 'Alba.XnaConvert.Loader.Xna10.ContentService'. Element: Alba.XnaConvert.Loader.Xna10.ContentService (ContractName="Alba.XnaConvert.Common.IContentService") -->  Alba.XnaConvert.Loader.Xna10.ContentService -->  DirectoryCatalog (Path=".")  (1: An exception occurred while trying to create an instance of type 'Alba.XnaConvert.Loader.Xna10.ContentService'. The method call is invalid.)
Detailed exception information:
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) The method call is invalid.

Resulting in: An exception occurred while trying to create an instance of type 'Alba.XnaConvert.Loader.Xna10.ContentService'.

Resulting in: Cannot activate part 'Alba.XnaConvert.Loader.Xna10.ContentService'.
Element: Alba.XnaConvert.Loader.Xna10.ContentService -->  Alba.XnaConvert.Loader.Xna10.ContentService -->  DirectoryCatalog (Path=".")

Resulting in: Cannot get export 'Alba.XnaConvert.Loader.Xna10.ContentService (ContractName="Alba.XnaConvert.Common.IContentService")' from part 'Alba.XnaConvert.Loader.Xna10.ContentService'.
Element: Alba.XnaConvert.Loader.Xna10.ContentService (ContractName="Alba.XnaConvert.Common.IContentService") -->  Alba.XnaConvert.Loader.Xna10.ContentService -->  DirectoryCatalog (Path=".")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Alba.XnaConvert.Program.GetContentService(String name, String version)
   at Alba.XnaConvert.Program.RunConvertVerb(ConvertSubOptions options)
   at Alba.XnaConvert.Program.MainInternal(String[] args)
   at Alba.XnaConvert.Program.Main(String[] args)
```

**Comment by rudecry** [comment]
im having the same problem :( please help!
